name: Coletar Noticias

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  coletar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Rodar coletor
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py